version: "2.1"
services:
  phets-animal-ms:
    container_name: phets-animal-ms
    image: phetsunal/phets-animal-ms
    build: .
    ports:
      - "4003:5000"
    depends_on:
      phets-animal-db:
        condition: service_healthy
    environment:
      DATABASE_USER: animalUser
      DATABASE_PASS: password
      DATABASE_URI: 172.17.0.1:3003
      DATABASE_NAME: animals
  phets-animal-db:
    image: mysql:5.7
    container_name: phets-animal-db
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    volumes:
     - phets-animal-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: animals123
      MYSQL_DATABASE: animals
      MYSQL_USER: animalUser
      MYSQL_PASSWORD: password
    ports:
      - "3003:3306"

volumes:
  phets-animal-volume: